jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'ARM64 with GPU'
    JobName: 'Linux_CI_Dev_ARM64'
    BuildCommand: './build.sh --config Release --update --build --build_wheel --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu'
    DoNugetPack:  'false'
    ArtifactName: 'drop-linux-arm64'
